### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by mcclint680** [talkingmoose/Choices-Packager#4]
M1 MBP, macOS Ventura 13.4.1(c)
When I run the script on any package that I know has multiple options like MS Office or Cisco Secure Client, I go through each step and at the end after it asks me to save the new installer I get a script error:

Can’t make POSIX path of «class cfol» "Choices XML Packager temp" of «class cfol» "TemporaryItems" of «class cfol» "T" of «class cfol» "91syqlcj2jv8fxz_gyrnvxw40000gq" of «class cfol» "3h" of «class cfol» "folders" of «class cfol» "var" of item "private" of «class sdsk» of application "Finder" into type Unicode text.

**Comment by talkingmoose** [comment]
@mcclint680 I’ve just spent some time updating the script and turning it into a droplet. Give it a test if you can still use it and let m know what you find.

**Comment by mcclint680** [comment]
I don’t see the download

**Comment by talkingmoose** [comment]
You don’t see the .scpt file under the code tab at the top? There’s not anything else. Download, open in Script Editor and save as an app. Then drag your package with choice options onto the app.

**Comment by mcclint680** [comment]
There we go. This version 2 works much better now. Thanks for your hard work.

**Comment by talkingmoose** [comment]
Great to hear! I did my testing with Microsoft Office for Mac. Curious which package you used.

**Comment by mcclint680** [comment]
I first tried it on MS Office then I tested it on Cisco Secure Client.

**Comment by talkingmoose** [comment]
Excellent! Two of the ones I’d hoped to hear.

Thanks so much!
